options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/flask-app1', '.' ]

  - name: 'gcr.io/cloud-builders/dockers'
    args: [ 'push', 'gcr.io/$PROJECT_ID/flask-app1']

  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - run 
    - image=gcr.io/$PROJECT_ID/flask-app1
    - location=us-central-c
    - cluster=flask
    - namespace=flask
